affgl.o: affgl.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h graphisme.h figure.h affgl.h
controle.o: controle.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h
courbe.o: courbe.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h
determ.o: determ.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 courbe.h gifs.h graphisme.h figure.h image.h determ.h
echantillon.o: echantillon.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h graphisme.h figure.h echantillon.h
echap.o: echap.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h graphisme.h image.h echap.h
figure.o: figure.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h graphisme.h figure.h
gifs.o: gifs.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h
graphisme.o: graphisme.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h graphisme.h
ifs.o: ifs.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h
image.o: image.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h graphisme.h \
 image.h
matrice.o: matrice.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h
o_eric.o: o_eric.c /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 t_eric.h util.h /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h \
 controle.h ifs.h gifs.h graphisme.h figure.h pov.h affgl.h image.h \
 /home/exco/NE/2.2/UTILITAIRES/s_string.h determ.h courbe.h
point.o: point.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h
pov.o: pov.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h graphisme.h figure.h pov.h
prod.o: prod.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h regle.h graphisme.h figure.h image.h echap.h determ.h pov.h \
 prod.h
regle.o: regle.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 regle.h
surface.o: surface.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 courbe.h
t_eric.o: t_eric.c /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h t_eric.h util.h \
 /home/exco/NE/2.2/COEUR/o_objet.h /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h point.h matrice.h controle.h ifs.h \
 gifs.h graphisme.h figure.h pov.h affgl.h image.h
util.o: util.c util.h /home/exco/NE/2.2/COEUR/o_objet.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/eprintf.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_base.h \
 /home/exco/NE/2.2/UTILITAIRES/codec_base.h \
 /home/exco/NE/2.2/UTILITAIRES/u_geometrie.h \
 /home/exco/NE/2.2/UTILITAIRES/codec.h \
 /home/exco/NE/2.2/UTILITAIRES/l_liste.h \
 /home/exco/NE/2.2/UTILITAIRES/u_memoire.h \
 /home/exco/NE/2.2/UTILITAIRES/u_widget.h \
 /home/exco/NE/2.2/UTILITAIRES/u_etat.h /home/exco/NE/2.2/TYPES/t_base.h \
 /home/exco/NE/2.2/TYPES/t_geometrie.h
