o_affiche_octree.o: o_affiche_octree.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
o_ajoute_pt.o: o_ajoute_pt.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_arbre.o: o_arbre.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/OBJETS/u_vue.h
o_bezier.o: o_bezier.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_bresenham.o: o_bresenham.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_convexe.o: o_convexe.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_decoupage.o: o_decoupage.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_ex_arbre.o: o_ex_arbre.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/OBJETS/u_vue.h
o_ex_bresenham.o: o_ex_bresenham.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_ex_decoupage.o: o_ex_decoupage.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_ex_plan.o: o_ex_plan.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/OBJETS/u_vue.h \
 /home/houssam/SVN/prog/NE/OBJETS/u_etat_courant.h
o_ex_rotation.o: o_ex_rotation.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/s_string.h
o_ex_translation.o: o_ex_translation.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/s_string.h
o_gpao_piece.o: o_gpao_piece.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_gpao_reserve.o: o_gpao_reserve.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/s_string.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_gpao_transporteur.o: o_gpao_transporteur.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_inter_bez_seg.o: o_inter_bez_seg.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_inter_octree.o: o_inter_octree.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
o_interseg.o: o_interseg.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_iso_surf.o: o_iso_surf.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/OBJETS/u_etat_courant.h
o_primitives.o: o_primitives.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/OBJETS/u_etat_courant.h
o_triangulation.o: o_triangulation.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_x_rotation.o: o_x_rotation.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/s_string.h
o_x_translation.o: o_x_translation.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/s_string.h
