o_ascenseur.o: o_ascenseur.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_creation.o: o_creation.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_gl.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
o_date.o: o_date.c /home/houssam/SVN/prog/NE/OBJETS/u_xt_interface.h \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/OBJETS/o_interface.h
o_destruction.o: o_destruction.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/s_string.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_inversion.o: o_inversion.c /home/houssam/SVN/prog/NE/TYPES/t_image.h \
 /home/houssam/SVN/prog/NE/TYPES/t_gl.h \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_polymorphisme.o: o_polymorphisme.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_raccourci.o: o_raccourci.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_s1.o: o_s1.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
o_s10.o: o_s10.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_s11.o: o_s11.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h t_segment.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s12.o: o_s12.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h t_segment.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s13.o: o_s13.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s14.o: o_s14.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_s15.o: o_s15.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s16.o: o_s16.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s17.o: o_s17.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/OBJETS/u_etat_courant.h
o_s18.o: o_s18.c /home/houssam/SVN/prog/NE/TYPES/t_gl.h \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_s19.o: o_s19.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s2.o: o_s2.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
o_s20.o: o_s20.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
o_s21.o: o_s21.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_s22.o: o_s22.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_graphique.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h
o_s23.o: o_s23.c /home/houssam/SVN/prog/NE/TYPES/t_image.h \
 /home/houssam/SVN/prog/NE/TYPES/t_gl.h \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s24.o: o_s24.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
o_s3.o: o_s3.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s4.o: o_s4.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s5.o: o_s5.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s6.o: o_s6.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s7.o: o_s7.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s8.o: o_s8.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_s9.o: o_s9.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
o_test_heritage.o: o_test_heritage.c \
 /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h
t_segment.o: t_segment.c /home/houssam/SVN/prog/NE/COEUR/o_objet.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/eprintf.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec_base.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_geometrie.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/codec.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/l_liste.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_memoire.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_widget.h \
 /home/houssam/SVN/prog/NE/UTILITAIRES/u_etat.h \
 /home/houssam/SVN/prog/NE/TYPES/t_base.h t_segment.h \
 /home/houssam/SVN/prog/NE/TYPES/t_geometrie.h
